"""Canonical deterministic reason codes for approvals, rejections, and gates."""

from __future__ import annotations

APPROVED = "APPROVED"

SYMBOL_NOT_IN_SCOPE = "SYMBOL_NOT_IN_SCOPE"
OUTSIDE_ENTRY_WINDOW = "OUTSIDE_ENTRY_WINDOW"
OR_NOT_READY = "OR_NOT_READY"
NO_BREAKOUT_TRIGGER = "NO_BREAKOUT_TRIGGER"
UNQUALIFIED_TREND = "UNQUALIFIED_TREND"
TIER1_LOCKOUT_ACTIVE = "TIER1_LOCKOUT_ACTIVE"
VOLUME_NOT_STRONG = "VOLUME_NOT_STRONG"
VWAP_SIDE_FILTER_FAILED = "VWAP_SIDE_FILTER_FAILED"
EMA_ALIGNMENT_FAILED = "EMA_ALIGNMENT_FAILED"
INVALID_ATR_14_5M = "INVALID_ATR_14_5M"
OR_WIDTH_SANITY_FAILED = "OR_WIDTH_SANITY_FAILED"
SCORE_BELOW_THRESHOLD = "SCORE_BELOW_THRESHOLD"

COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
DAILY_LOSS_HALT = "DAILY_LOSS_HALT"
POSITION_ALREADY_OPEN = "POSITION_ALREADY_OPEN"
DATA_NOT_OK = "DATA_NOT_OK"
FAMILY_FREEZE_ACTIVE = "FAMILY_FREEZE_ACTIVE"
PENDING_ENTRY_CANCELLED_LOCKOUT = "PENDING_ENTRY_CANCELLED_LOCKOUT"
SYMBOL_POSITION_CAP = "SYMBOL_POSITION_CAP"
FAMILY_OPEN_RISK_CAP = "FAMILY_OPEN_RISK_CAP"
TOTAL_OPEN_RISK_CAP = "TOTAL_OPEN_RISK_CAP"
INVALID_STOP_DISTANCE = "INVALID_STOP_DISTANCE"
INVALID_RISK_PER_CONTRACT = "INVALID_RISK_PER_CONTRACT"
SIZE_LT_ONE = "SIZE_LT_ONE"
HARD_RISK_CAP_EXCEEDED = "HARD_RISK_CAP_EXCEEDED"
MICRO_INSTRUMENT_NOT_FOUND = "MICRO_INSTRUMENT_NOT_FOUND"
SIZE_LT_ONE_AFTER_MICRO_ROUTING = "SIZE_LT_ONE_AFTER_MICRO_ROUTING"

CALENDAR_LOCKOUT = "CALENDAR_LOCKOUT"

ALL_REASON_CODES: frozenset[str] = frozenset(
    {
        APPROVED,
        SYMBOL_NOT_IN_SCOPE,
        OUTSIDE_ENTRY_WINDOW,
        OR_NOT_READY,
        NO_BREAKOUT_TRIGGER,
        UNQUALIFIED_TREND,
        TIER1_LOCKOUT_ACTIVE,
        VOLUME_NOT_STRONG,
        VWAP_SIDE_FILTER_FAILED,
        EMA_ALIGNMENT_FAILED,
        INVALID_ATR_14_5M,
        OR_WIDTH_SANITY_FAILED,
        SCORE_BELOW_THRESHOLD,
        COOLDOWN_ACTIVE,
        DAILY_LOSS_HALT,
        POSITION_ALREADY_OPEN,
        DATA_NOT_OK,
        FAMILY_FREEZE_ACTIVE,
        PENDING_ENTRY_CANCELLED_LOCKOUT,
        SYMBOL_POSITION_CAP,
        FAMILY_OPEN_RISK_CAP,
        TOTAL_OPEN_RISK_CAP,
        INVALID_STOP_DISTANCE,
        INVALID_RISK_PER_CONTRACT,
        SIZE_LT_ONE,
        HARD_RISK_CAP_EXCEEDED,
        MICRO_INSTRUMENT_NOT_FOUND,
        SIZE_LT_ONE_AFTER_MICRO_ROUTING,
        CALENDAR_LOCKOUT,
    }
)
